resource "template_dir" "config" {
  source_dir      = "${path.module}/templates"
  destination_dir = "${path.cwd}/files"

  vars {
    project                    = "${var.project}"
    deployment_tag             = "${var.env_name}-vms"
    auth_json                  = "${base64decode(google_service_account_key.opsman_service_account_key.private_key)}"
    azs                        = "${join(",", var.zones)}"
    network_name               = "${google_compute_network.pcf-network.name}"
    singleton_az               = "${var.zones[0]}"
    subnet_mgmt_name           = "${google_compute_subnetwork.management-subnet.name}"
    subnet_mgmt_google_name    = "${google_compute_network.pcf-network.name}/${google_compute_subnetwork.management-subnet.name}/${var.region}"
    subnet_mgmt_cidr           = "${google_compute_subnetwork.management-subnet.ip_cidr_range}"
    subnet_mgmt_reserved       = "${cidrhost(google_compute_subnetwork.management-subnet.ip_cidr_range, 1)}-${cidrhost(google_compute_subnetwork.management-subnet.ip_cidr_range, 9)}"
    subnet_mgmt_gateway        = "${google_compute_subnetwork.management-subnet.gateway_address}"
    subnet_pas_name            = "${google_compute_subnetwork.pas-subnet.name}"
    subnet_pas_google_name     = "${google_compute_network.pcf-network.name}/${google_compute_subnetwork.pas-subnet.name}/${var.region}"
    subnet_pas_cidr            = "${google_compute_subnetwork.pas-subnet.ip_cidr_range}"
    subnet_pas_reserved        = "${cidrhost(google_compute_subnetwork.pas-subnet.ip_cidr_range, 1)}-${cidrhost(google_compute_subnetwork.pas-subnet.ip_cidr_range, 9)}"
    subnet_pas_gateway         = "${google_compute_subnetwork.pas-subnet.gateway_address}"
    subnet_pas_svc_name        = "${google_compute_subnetwork.services-subnet.name}"
    subnet_pas_svc_google_name = "${google_compute_network.pcf-network.name}/${google_compute_subnetwork.services-subnet.name}/${var.region}"
    subnet_pas_svc_cidr        = "${google_compute_subnetwork.services-subnet.ip_cidr_range}"
    subnet_pas_svc_reserved    = "${cidrhost(google_compute_subnetwork.services-subnet.ip_cidr_range, 1)}-${cidrhost(google_compute_subnetwork.services-subnet.ip_cidr_range, 9)}"
    subnet_pas_svc_gateway     = "${google_compute_subnetwork.services-subnet.gateway_address}"
    subnet_pks_name            = "${module.pks.pks_subnet_name}"
    subnet_pks_google_name     = "${google_compute_network.pcf-network.name}/${module.pks.pks_subnet_name}/${var.region}"
    subnet_pks_cidr            = "${module.pks.pks_subnet_cidrs}"
    subnet_pks_reserved        = "${cidrhost(module.pks.pks_subnet_cidrs, 1)}-${cidrhost(module.pks.pks_subnet_cidrs, 9)}"
    subnet_pks_gateway         = "${module.pks.pks_subnet_gateway}"
    subnet_pks_svc_name        = "${module.pks.pks_services_subnet_name}"
    subnet_pks_svc_google_name = "${google_compute_network.pcf-network.name}/${module.pks.pks_services_subnet_name}/${var.region}"
    subnet_pks_svc_cidr        = "${module.pks.pks_services_subnet_cidrs}"
    subnet_pks_svc_reserved    = "${cidrhost(module.pks.pks_services_subnet_cidrs, 1)}-${cidrhost(module.pks.pks_services_subnet_cidrs, 9)}"
    subnet_pks_svc_gateway     = "${module.pks.pks_services_subnet_gateway}"

    pks_wildcard                          = "*.${var.env_name}.${var.dns_suffix}"
    pks_hostname                          = "${module.pks.domain}"
    pks_master_node_service_account_email = "${module.pks.pks_master_node_service_account_email}"
    pks_worker_node_service_account_email = "${module.pks.pks_worker_node_service_account_email}"
  }
}
