#!/bin/bash -e

authenticate_om() {
  export OM_TARGET="https://$(terraform output ops_manager_dns)"
  export OM_USERNAME="admin"
  export OM_PASSWORD="$1"
}

main() {
  local path=${1?"Path is required (e.g. terraforming-pas, terraforming-pks, terraforming-control-plane)"}
  local password=${2?"OpsManager password is required."}

  pushd $PROJECT_DIR/$path > /dev/null
    RAW_JSON=$(jq -e --raw-output '.modules[0].outputs | map_values(.value)' terraform.tfstate)
    WITH_CERT=$(echo ${RAW_JSON} | jq --arg terraformingca "${CA_CERT}" '. + {terraforming_ca_cert: $terraformingca}')

    authenticate_om "${password}"

    om -k configure-authentication -dp "${OM_PASSWORD}"
    om -k configure-director --config <(texplate execute "${PROJECT_DIR}/ci/assets/template/director-config.yml" -f  <(echo "${WITH_CERT}") -o yaml)
  popd > /dev/null
}

main "$@"
